#!/usr/bin/env python3
"""
crystallize.py - Rule Compiler for Self-Improving Developer Agent

Scans the episodic memory store (experience_store.jsonl), aggregates heuristics
by engineering domain, ranks them by frequency and severity, and compiles them
into an authoritative Antigravity workspace rule:
  .agents/rules/learned_rules.md

This ensures lessons become permanent, living guidelines that guide every agent
in the workspace without manual reminder.
Pure Python standard library.
"""

import os
import sys
import json
import argparse
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict, Any

DEFAULT_STORE = Path(__file__).parent / "store" / "experience_store.jsonl"


def find_workspace_root(start: Path = None) -> Path:
    """
    Walk upward from this file to the nearest directory that owns an `.agents/` folder,
    so the compiled rules land where agents actually read them no matter how deeply
    this repo is nested (e.g. C:\\AI-Workspace\\Projects\\agent-memory -> C:\\AI-Workspace).
    Falls back to the parent of this repo when no `.agents/` directory exists yet.
    """
    here = (start or Path(__file__)).resolve()
    for candidate in here.parents:
        if (candidate / ".agents").is_dir():
            return candidate
    return here.parent.parent


WORKSPACE_ROOT = find_workspace_root()
DEFAULT_RULES_OUTPUT = WORKSPACE_ROOT / ".agents" / "rules" / "learned_rules.md"


def load_memories(store_path: Path) -> List[Dict[str, Any]]:
    """Load all records from JSONL."""
    if not store_path.exists():
        return []
    records = []
    with open(store_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return records


def build_markdown_rules(records: List[Dict[str, Any]]) -> str:
    """Compile records into a structured Antigravity rules document."""
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Group by domain
    domains: Dict[str, List[Dict[str, Any]]] = {}
    for r in records:
        dom = r.get("domain", "general").title()
        if dom not in domains:
            domains[dom] = []
        domains[dom].append(r)

    # Sort records inside each domain by (frequency, severity rank)
    sev_rank = {"critical": 4, "high": 3, "medium": 2, "low": 1}
    for dom in domains:
        domains[dom].sort(
            key=lambda x: (x.get("frequency", 1), sev_rank.get(x.get("severity", "medium"), 2)),
            reverse=True
        )

    lines = [
        "# Workspace Learned Rules & Heuristics",
        "",
        "> [!IMPORTANT]",
        "> **Auto-Generated by Self-Improving Developer Agent Engine** (`agent-memory/crystallize.py`).",
        "> These rules reflect hard-won lessons from real-world bugs, regression post-mortems, and user corrections.",
        f"> **Last Compiled:** {now_str} | **Total Active Heuristics:** {len(records)}",
        "",
        "All AI coding agents operating in this workspace MUST adhere to these distilled heuristics before generating or modifying code.",
        "",
        "---",
        ""
    ]

    for dom, items in sorted(domains.items()):
        lines.append(f"## {dom} Heuristics")
        lines.append("")
        for item in items:
            rule_id = item.get("id", "MEM-???")
            sev = item.get("severity", "medium").upper()
            freq = item.get("frequency", 1)
            rule = item.get("permanent_rule", "").strip()
            trigger = item.get("trigger", "").strip()
            symptom = item.get("symptom", "").strip()
            tags = ", ".join(f"`{t}`" for t in item.get("tags", []))

            badge = f"**[{rule_id}]** `Severity: {sev}` `Observed: {freq}x`"
            lines.append(f"### {badge}")
            lines.append(f"- **Mandatory Rule**: {rule}")
            if trigger:
                lines.append(f"- **When It Applies**: {trigger}")
            if symptom:
                lines.append(f"- **Avoided Failure / Symptom**: {symptom}")
            if tags:
                lines.append(f"- **Keywords**: {tags}")
            lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("## How to Update These Rules")
    lines.append("1. **Log a new post-mortem**:")
    lines.append("   ```powershell")
    lines.append('   python agent-memory/reflect.py --domain "<domain>" --trigger "<scenario>" --symptom "<bug>" --root-cause "<reason>" --rule "<permanent rule>" --tags "<tag1,tag2>"')
    lines.append("   ```")
    lines.append("2. **Recompile active rules**:")
    lines.append("   ```powershell")
    lines.append("   python agent-memory/crystallize.py")
    lines.append("   ```")
    lines.append("")

    return "\n".join(lines)


def crystallize(store_path: Path = DEFAULT_STORE, output_path: Path = DEFAULT_RULES_OUTPUT) -> Path:
    """Compile memories into markdown rules file."""
    memories = load_memories(store_path)
    content = build_markdown_rules(memories)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    return output_path


def main():
    parser = argparse.ArgumentParser(description="Compile episodic memories into workspace rules markdown.")
    parser.add_argument("--store", help="Path to experience_store.jsonl")
    parser.add_argument("--output", "-o", help="Path to destination markdown file (default: .agents/rules/learned_rules.md)")

    args = parser.parse_args()
    store_path = Path(args.store) if args.store else DEFAULT_STORE
    output_path = Path(args.output) if args.output else DEFAULT_RULES_OUTPUT

    try:
        if sys.platform == "win32":
            sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    out = crystallize(store_path=store_path, output_path=output_path)
    print(f"[OK] Crystallized {len(load_memories(store_path))} memories into: {out}")


if __name__ == "__main__":
    main()
